import { MaterialOption, LayerQualityOption, PrinterDevice, DeliveryMethod } from '../types';

export const MATERIALS: MaterialOption[] = [
  {
    id: 'PLA_PLUS',
    name: 'PLA+ Professional',
    technology: 'FDM',
    densityGramsPerCm3: 1.24,
    costPerGram: 0.08,
    description: 'High dimensional accuracy, crisp surface detail, low warp. Ideal for prototypes, enclosures, and visual models.',
    heatResistance: '55°C',
    tensileStrength: '50 MPa',
    colors: [
      { name: 'Matte Obsidian Black', hex: '#1e2022' },
      { name: 'Signal White', hex: '#f8fafc' },
      { name: 'Galaxy Silver', hex: '#94a3b8' },
      { name: 'Signal Orange', hex: '#ea580c' },
      { name: 'Prusa Cyan Blue', hex: '#0284c7' },
      { name: 'Forest Olive', hex: '#15803d' },
    ],
  },
  {
    id: 'PETG_CF',
    name: 'PETG Carbon Fiber',
    technology: 'FDM',
    densityGramsPerCm3: 1.29,
    costPerGram: 0.16,
    description: 'Carbon fiber reinforced. High rigidity, excellent chemical resistance, temperature resistance, and premium matte texture.',
    heatResistance: '75°C',
    tensileStrength: '68 MPa',
    colors: [
      { name: 'Matte Charcoal Black', hex: '#18181b' },
      { name: 'Gunmetal Slate', hex: '#475569' },
    ],
  },
  {
    id: 'ABS_PRO',
    name: 'ABS Industrial Pro',
    technology: 'FDM',
    densityGramsPerCm3: 1.05,
    costPerGram: 0.12,
    description: 'Impact resistant, sandable, and heat resistant. Suitable for functional automotive & mechanical end-use components.',
    heatResistance: '95°C',
    tensileStrength: '43 MPa',
    colors: [
      { name: 'Industrial Grey', hex: '#64748b' },
      { name: 'Gloss Black', hex: '#0f172a' },
      { name: 'Safety Red', hex: '#dc2626' },
    ],
  },
  {
    id: 'TPU_FLEX',
    name: 'TPU 95A Flexible',
    technology: 'FDM',
    densityGramsPerCm3: 1.21,
    costPerGram: 0.18,
    description: 'Semi-flexible rubber-like elastomer. Exceptional abrasion and tear resistance. Great for gaskets, bumpers, grips.',
    heatResistance: '60°C',
    tensileStrength: '35 MPa',
    colors: [
      { name: 'Stealth Black', hex: '#27272a' },
      { name: 'Translucent Clear', hex: '#e2e8f0' },
      { name: 'Vibrant Yellow', hex: '#eab308' },
    ],
  },
  {
    id: 'TOUGH_RESIN',
    name: 'SLA Ultra-Tough Resin',
    technology: 'SLA_RESIN',
    densityGramsPerCm3: 1.18,
    costPerGram: 0.28,
    description: 'Liquid photopolymer cured with 405nm UV laser. Glass-smooth finish with microscopic layer details for jewelry & precision molds.',
    heatResistance: '72°C',
    tensileStrength: '58 MPa',
    colors: [
      { name: 'Onyx Black', hex: '#09090b' },
      { name: 'Smoky Amber Translucent', hex: '#d97706' },
      { name: 'Ceramic Grey', hex: '#cbd5e1' },
    ],
  },
  {
    id: 'NYLON_PA12',
    name: 'SLS Nylon PA12',
    technology: 'SLS_NYLON',
    densityGramsPerCm3: 1.01,
    costPerGram: 0.42,
    description: 'Powder-bed laser sintered. Self-supporting, isotropic strength in all directions, industrial manufacturing grade.',
    heatResistance: '140°C',
    tensileStrength: '48 MPa',
    colors: [
      { name: 'Raw Natural Grey', hex: '#a1a1aa' },
      { name: 'Deep Dyed Black', hex: '#18181b' },
    ],
  },
];

export const LAYER_QUALITIES: LayerQualityOption[] = [
  {
    id: 'ULTRA_FINE',
    label: 'Ultra Fine (0.08mm)',
    heightMm: 0.08,
    speedMultiplier: 2.2,
    costMultiplier: 1.45,
    description: 'Virtually invisible layer lines. Ideal for miniature figurines and presentation models.',
  },
  {
    id: 'FINE',
    label: 'Fine (0.16mm)',
    heightMm: 0.16,
    speedMultiplier: 1.4,
    costMultiplier: 1.2,
    description: 'Smooth surfaces with high fidelity curves. Great for consumer gadgets.',
  },
  {
    id: 'STANDARD',
    label: 'Standard (0.20mm)',
    heightMm: 0.20,
    speedMultiplier: 1.0,
    costMultiplier: 1.0,
    description: 'Optimal balance between printing speed, structural strength, and surface finish.',
  },
  {
    id: 'DRAFT',
    label: 'Draft Rapid (0.28mm)',
    heightMm: 0.28,
    speedMultiplier: 0.7,
    costMultiplier: 0.85,
    description: 'Fast turn-around for preliminary fit tests and quick mechanical prototypes.',
  },
];

export const DELIVERY_OPTIONS = [
  {
    id: 'STANDARD_TRACKED' as DeliveryMethod,
    name: 'Standard Tracked Courier',
    time: '2 - 4 Business Days',
    price: 8.5,
    carrier: 'DHL Ground / Postal Priority',
    description: 'Door-to-door tracking with automated dispatch SMS & email alerts.',
  },
  {
    id: 'EXPRESS_COURIER' as DeliveryMethod,
    name: 'Express Priority Courier',
    time: 'Next Day Delivery',
    price: 18.0,
    carrier: 'FedEx Express / DHL Express',
    description: 'Guaranteed next business day delivery with signature confirmation.',
  },
  {
    id: 'SAME_DAY_LOCAL' as DeliveryMethod,
    name: 'Same-Day City Dispatch',
    time: 'Under 6 Hours',
    price: 24.0,
    carrier: 'Direct City Courier',
    description: 'Direct courier delivery directly from our print workshop to your address.',
  },
  {
    id: 'WORKSHOP_PICKUP' as DeliveryMethod,
    name: 'Workshop Self-Pickup',
    time: 'Ready upon completion',
    price: 0.0,
    carrier: 'Print Lab Reception',
    description: 'Collect directly from our printing workshop with zero shipping fees.',
  },
];

export const INITIAL_PRINTERS: PrinterDevice[] = [
  {
    id: 'PRN-01',
    name: 'Bambu Lab X1-Carbon #1',
    modelName: 'Bambu Lab X1-Carbon AMS',
    technology: 'FDM',
    status: 'PRINTING',
    buildVolumeMm: { x: 256, y: 256, z: 256 },
    activeOrderId: 'ORD-8419',
    currentProgressPercent: 68,
    nozzleTempC: 220,
    targetNozzleTempC: 220,
    bedTempC: 60,
    targetBedTempC: 60,
    remainingTimeMinutes: 74,
  },
  {
    id: 'PRN-02',
    name: 'Prusa MK4 Nextruder #2',
    modelName: 'Original Prusa MK4',
    technology: 'FDM',
    status: 'IDLE',
    buildVolumeMm: { x: 250, y: 210, z: 220 },
    nozzleTempC: 24,
    targetNozzleTempC: 0,
    bedTempC: 23,
    targetBedTempC: 0,
  },
  {
    id: 'PRN-03',
    name: 'Voron 2.4 High-Temp #3',
    modelName: 'Voron 2.4 R2 350mm',
    technology: 'FDM',
    status: 'PRINTING',
    buildVolumeMm: { x: 350, y: 350, z: 350 },
    activeOrderId: 'ORD-8392',
    currentProgressPercent: 42,
    nozzleTempC: 255,
    targetNozzleTempC: 255,
    bedTempC: 105,
    targetBedTempC: 105,
    remainingTimeMinutes: 195,
  },
  {
    id: 'PRN-04',
    name: 'Elegoo Saturn 4 Ultra #4',
    modelName: 'Elegoo Saturn 4 12K MSLA',
    technology: 'SLA_RESIN',
    status: 'IDLE',
    buildVolumeMm: { x: 218, y: 122, z: 220 },
    nozzleTempC: 30,
    targetNozzleTempC: 30,
    bedTempC: 30,
    targetBedTempC: 30,
  },
];
